### ISSUE TITLE
Add Nikki Zeichner bio to team page

### ISSUE THREAD

**Issue by laurenryu** [GovLab/GovLab.org-Site#1]
Nikki Zeichner is a Fellow working in strategy and design capacities for the GovLab Academy. She is an MS candidate in Integrated Digital Media at NYU’s Engineering School and holds a JD from CUNY School of Law as well as a BA cum laude in philosophy from Barnard College, Columbia University. Before returning to study technology at NYU in the fall of 2013, Nikki worked as a criminal defense attorney representing clients charged with state and federal offenses in New York City. She has over a decade of experience advocating on behalf of marginalized individuals and communities in civil and criminal contexts. You can follow her on Twitter @nikzei.

**Comment by luisdaniel** [comment]
Thanks for entering this on github. 

I'll do this no problem, but we should assign someone who can be in charge of these small easy changes. Any ideas?

**Comment by luisdaniel** [comment]
Also, does she have a headshot?

**Comment by nikzei** [comment]
Do you guys want head shots to be somewhat uniform? I don't have any that fit the same clean, light aesthetic . . .Happy to take one in the space whenever and go ahead without one for now. Thanks!

**Comment by laurenryu** [comment]
We might be retaking all of the headshots.  Let's get the bio up ASAP and
then we'll get a picture when you're in or with the next round of
headshots.

**Comment by luisdaniel** [comment]
I'll still need something for people to click on. Can you just give me any picture you want to use so I can add you?

**Comment by nikzei** [comment]
![nikkiprofilepic](https://cloud.githubusercontent.com/assets/4856920/3926653/6861f76e-23f3-11e4-9b13-5b94b5488cf7.png)

**Comment by luisdaniel** [comment]
done.
