### ISSUE TITLE
Add Erika bio and pic to site

### ISSUE THREAD

**Issue by erikalharris** [GovLab/GovLab.org-Site#11]
Erika Harris is the Program Administrator at The GovLab. She joins
GovLab from the NYU Office of Global Programs where she managed the
financial operations and budgeting for NYU's global sites. Prior to
Global, she provided academic and administrative support at the NYU
Center for European and Mediterranean Studies. She has previously
worked in healthcare administration, at a microfinance startup and in
New York City Council.

Erika is currently pursuing a MPA at NYU Wagner where she specializes
in International Policy and Finance. Her research interests include
international development, financial inclusion and environmental
policy. She holds a MA in French Studies from NYU where she researched
immigration policy and human rights in the postcolonial context.

Erika is interested in how data and technology can improve climate
governance and climate change mitigation and adaption strategies
locally and internationally.

![10376256_10102891484892899_7674885533525664273_n](https://cloud.githubusercontent.com/assets/8977421/4478303/5d72b904-4984-11e4-823d-0816270fcb6f.jpg)

**Comment by luisdaniel** [comment]
Done! 
I know, we have a really crappy About page.. It's on our list of to-do's.
