### ISSUE TITLE
Adding bio to team page

### ISSUE THREAD

**Issue by sannon** [GovLab/GovLab.org-Site#12]
Hey Luis,

Please add my bio (below) to the team page. Thanks!

Shruti H. Sannon's research focuses on Internet governance, digital rights, and technological innovation in decision-making processes. Prior to the GovLab, Shruti conducted extensive research and ethnographic fieldwork in multiple developed and developing countries. She used insights from her research to create brand and communications strategies for multinational clients from a diverse range of industries.

She holds a Master of Arts degree in Media, Culture, and Communication from New York University, with a specialization in Technology and Society. Her Master's thesis focused on online privacy and explored the application of behavioral science towards designing more secure environments online.

You can follow her on Twitter @shsannon.

**Comment by luisdaniel** [comment]
done. If you want to add a picture, past one here. Make sure it's 3:2 ration
