### ISSUE TITLE
Bios

### ISSUE THREAD

**Issue by sverhulst** [GovLab/GovLab.org-Site#13]
Is there no way to share my bio from the govlab website without having folks to scroll to the end of http://thegovlab.org/about/team/ ??

**Comment by luisdaniel** [comment]
You, Beth, Alan, and Joel still have their individual pages. The original links still work (and I'll link to your names and pics). I kept them because I thought this would come up. 

As for the team page, I can put you guys at the top if you want.

**Comment by sverhulst** [comment]
What is the link?

Stefaan Verhulst
Co-Founder and Chief of R&D, The Governance Lab @ NYU
@sverhulst; @thegovlab
Sverhulst@nyu.edu; stefaan@thegovlab.org
NYU School of Engineering: http://thegovlab.org/contact-us/

The GovLab: http://www.thegovlab.org http://www.thegovlab.org/
The GovLab Blog: http://www.thegovlab.org/blog/
The GovLab Digest: http://www.thegovlab.org/govlab-digest/
The GovLab Academy: http://www.thegovlabacademy.org/
The GovLab Knowledge Base: http://thegovlab.org/wiki/Main_Page
Opening Governance Research Network: http://www.opening-governance.org/

From:  Luis notifications@github.com
Reply-To:  "GovLab/GovLab.org-Site"
<reply@reply.git
hub.com>
Date:  Thursday, October 16, 2014 11:06 AM
To:  "GovLab/GovLab.org-Site" GovLab.org-Site@noreply.github.com
Cc:  Stefaan Verhulst sverhulst@nyu.edu
Subject:  Re: [GovLab.org-Site] Bios (#13)

You, Beth, Alan, and Joel still have their individual pages. The original
links still work (and I'll link to your names and pics). I kept them because
I thought this would come up.

As for the team page, I can put you guys at the top if you want.

‹
Reply to this email directly or view it on GitHub
https://github.com/GovLab/GovLab.org-Site/issues/13#issuecomment-59376359
.
{"@context":"http://schema.org","@type":"EmailMessage","description":"View
this Issue on 
GitHub","action":{"@type":"ViewAction","url":"https://github.com/GovLab/GovL
ab.org-Site/issues/13#issuecomment-59376359","name":"View Issue"}}

**Comment by luisdaniel** [comment]
http://thegovlab.org/about/team/stefaan-verhulst/
