### ISSUE TITLE
Add 10/29 Ideas Lunch

### ISSUE THREAD

**Issue by elh266** [GovLab/GovLab.org-Site#14]
Hey,

Could you add the 10/29 Ideas Lunch info to our site?

Thanks!

![logo](https://cloud.githubusercontent.com/assets/9371726/4760263/7a7cfb2e-5aee-11e4-8f7c-3c7996d24477.jpg)

​

Register here ("here" should be linked to: https://www.eventbrite.com/e/govlab-ideas-lunch-wlucy-kimbell-tickets-13878760747)

The social design moment: Reflections on the intersections between design, public policy and social innovation

TALK DESCRIPTION: In this talk, Lucy Kimbell will share findings from the recently published report she co-authored mapping the emergence of "social" design and reflect on the intersections between academic research, policy, activism and social innovation. This report was commissioned by the UK's Arts and Humanities Research Council to inform strategy about research funding.
http://mappingsocialdesign.org/2014/10/09/social-design-futures-report/

BIO: Lucy Kimbell is a researcher, educator and designer. She is currently AHRC Research Fellow in the Cabinet Office Policy Lab and principal research fellow at the University of Brighton. She is also Associate Fellow at Said Business School, University of Oxford, where she has been teaching service design on the MBA since 2005. Lucy's Service Innovation Handbook will be published by BIS Publishers in early 2015. Lucy tweets @lixindex.

Lunch will be served.  Please RSVP so we have accurate numbers for food.

**Comment by luisdaniel** [comment]
[This picture needs more jpeg](https://www.youtube.com/watch?v=j5nZhf8SjXw)

**Comment by elh266** [comment]
[?] Did I do it wrong?

On Thu, Oct 23, 2014 at 4:32 PM, Luis notifications@github.com wrote:

> This picture needs more jpeg https://www.youtube.com/watch?v=j5nZhf8SjXw
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GovLab/GovLab.org-Site/issues/14#issuecomment-60304104
> .

## 

Best regards,

Erika Harris
Program Administrator
The Governance Lab
2 Metro Tech Center, 9th Floor
Brooklyn, NY 11201
office: 718.260.3150
mobile: 516.680.7584

New York University Robert F. Wagner Graduate School of Public Service
Master of Public Administration | International Specialization | Candidate
2016

**Comment by luisdaniel** [comment]
haha you did it right but whoever made that graphic needs to give you a bigger one. That picture is tiny.
Need at least 593x234 or anything larger in that same ratio. 
Presumably Claudio did the graphic? Ask him for a bigger version, he should have it.

**Comment by elh266** [comment]
Antony made it as a PDF but you can only upload jpegs on Eventbrite so I
made that one. Could I send you Antony's PDF?

On Thu, Oct 23, 2014 at 4:54 PM, Luis notifications@github.com wrote:

> haha you did it right but whoever made that graphic needs to give you a
> bigger one. That picture is tiny.
> Need at least 593x234 or anything larger in that same ratio.
> Presumably Claudio did the graphic? Ask him for a bigger version, he
> should have it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GovLab/GovLab.org-Site/issues/14#issuecomment-60307540
> .

## 

Best regards,

Erika Harris
Program Administrator
The Governance Lab
2 Metro Tech Center, 9th Floor
Brooklyn, NY 11201
office: 718.260.3150
mobile: 516.680.7584

New York University Robert F. Wagner Graduate School of Public Service
Master of Public Administration | International Specialization | Candidate
2016

**Comment by luisdaniel** [comment]
JPG is fine, it just needs to be larger. Tell Antony to give you a larger pic.
