### ISSUE TITLE
Lucy Kimbell movement to moment

### ISSUE THREAD

**Issue by elh266** [GovLab/GovLab.org-Site#15]
Could you update Lucy's talk on the site so it says "moment" instead of "movement?" Attached is Antony's updated graphic as a jpg.

![ideas-lunch-banners22](https://cloud.githubusercontent.com/assets/9371726/4869965/96d25034-6157-11e4-8b26-1f758d82f3ab.jpg)

**Comment by luisdaniel** [comment]
done

**Comment by elh266** [comment]
Thanks!

On Mon, Nov 3, 2014 at 10:54 AM, Luis notifications@github.com wrote:

> Closed #15 https://github.com/GovLab/GovLab.org-Site/issues/15.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GovLab/GovLab.org-Site/issues/15#event-187417779.

## 

Best regards,

Erika Harris
Program Administrator
The Governance Lab
2 Metro Tech Center, 9th Floor
Brooklyn, NY 11201
office: 718.260.3150
mobile: 516.680.7584

New York University Robert F. Wagner Graduate School of Public Service
Master of Public Administration | International Specialization | Candidate
2016
