### ISSUE TITLE
titles

### ISSUE THREAD

**Issue by sverhulst** [GovLab/GovLab.org-Site#17]
why are suddenly all titles on the website underlined?

**Comment by luisdaniel** [comment]
because for the Internet Governance Map posts we needed a way to distinguish between titles and links. so Claudio made all the links underlined. 
I'll ask if he can change it so only links from Net Gov Map post are underlined, but the rest stay the same.

**Comment by sverhulst** [comment]
Yes - that would be great - thanks

**Comment by luisdaniel** [comment]
fixed
