### ISSUE TITLE
Add 12/5 Ideas Lunch to site

### ISSUE THREAD

**Issue by elh266** [GovLab/GovLab.org-Site#18]
Hey,

Could you add the 12/5 Ideas Lunch info to our site?

Thanks!

![ideas-lunch-banners15](https://cloud.githubusercontent.com/assets/9371726/5187074/8d04e978-7498-11e4-8901-e412a99b80a0.jpg)

Designing Services with the Public
Chelsea Mauldin has worked extensively with New York City and federal agencies, for whom she’s designed services with affordable-housing applicants, seniors enrolling in Medicare, and public-school students with disabilities, among others. In this talk, Chelsea will describe experiences and outcomes from applying collaborative design strategies in a public-interest context.

Bio:
Chelsea Mauldin is a social scientist and strategic designer with a focus on public-sector innovation. She directs the Public Policy Lab, a New York City nonprofit dedicated to improving the design and delivery of public services. 

The Public Policy Lab partners with government agencies to develop more satisfying and effective services through user-centered research, design prototyping, testing, and evaluation. Find out more on PPL's website, www.publicpolicylab.org, or on Twitter at @publicpolicylab. 

Previously, Chelsea's led a community-development organization, overseen government partnerships at a public-space advocacy nonprofit, and consulted to municipal and federal agencies. She is a graduate of the University of California at Berkeley and the London School of Economics.

Lunch will be served.  Please RSVP so we have accurate numbers for food.

**Comment by luisdaniel** [comment]
just getting to this. is there an eventbrite link to the event?

**Comment by elh266** [comment]
Yes thanks!

https://www.eventbrite.com/e/govlab-ideas-lunch-wchelsea-mauldin-tickets-14225102665

On Mon, Dec 1, 2014 at 11:38 AM, Luis notifications@github.com wrote:

> just getting to this. is there an eventbrite link to the event?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GovLab/GovLab.org-Site/issues/18#issuecomment-65092692
> .

## 

Best regards,

Erika Harris
Program Administrator
The Governance Lab
2 Metro Tech Center, 9th Floor
Brooklyn, NY 11201
office: 718.260.3150
mobile: 516.680.7584
thegovlab.org

New York University Robert F. Wagner Graduate School of Public Service
Master of Public Administration | International Specialization | Candidate
2016

**Comment by luisdaniel** [comment]
you'll need to remind me to move John Wilbanks up after the Chelsea ideas lunch so that John appears on top.
