### ISSUE TITLE
Update Beth's bio

### ISSUE THREAD

**Issue by laurenryu** [GovLab/GovLab.org-Site#2]
Beth Simone Noveck directs The Governance Lab and its MacArthur Research Network on Opening Governance.  Funded by the John D. and Catherine T. MacArthur Foundation,  the John S. and James L. Knight Foundation and Google.org, the GovLab strives to improve people’s lives by changing how we govern. The GovLab designs and tests technology, policy and strategies for fostering more open and collaborative approaches to strengthen the ability of people and institutions to work together to solve problems, make decisions, resolve conflict and govern themselves more effectively and legitimately.

The Jerry Hultin Global Network Visiting Professor at New York University’s Polytechnic School of Engineering, she was formerly the Jacob K. Javits Visiting Professor at the Robert F. Wagner Graduate School of Public Service and a visiting professor at the MIT Media Lab. Beth is a professor of law at New York Law School. She served in the White House as the first United States Deputy Chief Technology Officer and director of the White House Open Government Initiative (2009-2011). UK Prime Minister David Cameron appointed her senior advisor for Open Government, and she served on the Obama-Biden transition team. Among projects she’s designed or collaborated on are Unchat, The Do Tank, Peer To Patent, Data.gov, Challenge.gov and the Gov Lab’s Living Labs and training platform, The Academy.

A graduate of Harvard University and Yale Law School, she serves on the Global Commission on Internet Governance and chairs the ICANN Strategy Panel on Multi-Stakeholder Innovation. She was named one of the “Foreign Policy 100″ by Foreign Policy, one of the “100 Most Creative People in Business” by Fast Company and one of the “Top Women in Technology” by Huffington Post.  She has also been honored by both the National Democratic Institute and Public Knowledge for her work in civic technology.

Beth is the author of Wiki Government: How Technology Can Make Government Better, Democracy Stronger and Citizens More Powerful, which has also appeared in Arabic, Russian, Chinese and in an audio edition, and co-editor of The State of Play: Law, Games and Virtual Worlds. Her next book Smart Citizens: Smarter State will appear with Harvard University Press. She tweets @bethnoveck.

**Comment by luisdaniel** [comment]
The next step will be to get people to do these types of small changes themselves : )
