### ISSUE TITLE
Ideas Lunch blogs linked to Ideas Lunch page

### ISSUE THREAD

**Issue by elh266** [GovLab/GovLab.org-Site#22]
Could you please make sure that the Ideas Lunch blogs are also hyperlinked with the events mentioned at http://thegovlab.org/ideas-lunch-page/? Thanks!

**Comment by luisdaniel** [comment]
It would be nice if the person who writes the blog post handles this....
maybe next time whenever they ask someone to write the blog post, also remind them to link it.

**Comment by elh266** [comment]
Thanks for that. You got it. Wasn't sure who was supposed to do it.

On Tue, Jan 13, 2015 at 1:26 PM, Luis notifications@github.com wrote:

> It would be nice if the person who writes the blog post handles this....
> maybe next time whenever they ask someone to write the blog post, also
> remind them to link it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GovLab/GovLab.org-Site/issues/22#issuecomment-69793027
> .

## 

Best regards,

Erika Harris
Program Administrator
The Governance Lab
2 MetroTech Center, 9th Floor
Brooklyn, NY 11201
office: 718.260.3150
mobile: 516.680.7584
thegovlab.org

New York University Robert F. Wagner Graduate School of Public Service
Master of Public Administration | International Specialization | Candidate
2016

**Comment by elh266** [comment]
BTW, this was a Stefaan request. Sorry about that and thanks for helping.

On Tue, Jan 13, 2015 at 1:54 PM, Erika Harris erika@thegovlab.org wrote:

> Thanks for that. You got it. Wasn't sure who was supposed to do it.
> 
> On Tue, Jan 13, 2015 at 1:26 PM, Luis notifications@github.com wrote:
> 
> > It would be nice if the person who writes the blog post handles this....
> > maybe next time whenever they ask someone to write the blog post, also
> > remind them to link it.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/GovLab/GovLab.org-Site/issues/22#issuecomment-69793027
> > .
> 
> ## 
> 
> Best regards,
> 
> Erika Harris
> Program Administrator
> The Governance Lab
> 2 MetroTech Center, 9th Floor
> Brooklyn, NY 11201
> office: 718.260.3150
> mobile: 516.680.7584
> thegovlab.org
> 
> New York University Robert F. Wagner Graduate School of Public Service
> Master of Public Administration | International Specialization | Candidate
> 2016

## 

Best regards,

Erika Harris
Program Administrator
The Governance Lab
2 MetroTech Center, 9th Floor
Brooklyn, NY 11201
office: 718.260.3150
mobile: 516.680.7584
thegovlab.org

New York University Robert F. Wagner Graduate School of Public Service
Master of Public Administration | International Specialization | Candidate
2016
