### ISSUE TITLE
Ideas Lunch blurb added to Events page

### ISSUE THREAD

**Issue by elh266** [GovLab/GovLab.org-Site#23]
Could you add the blurb below to the top of the events page (http://thegovlab.org/events/)

The GovLab Ideas Lunches (linked:
http://thegovlab.org/ideas-lunch-page/) are monthly talks where
thought leaders from a range of disciplinary backgrounds and sectors
join GovLab staff and members of the NYU community to share their
views, expertise, and experiences about how innovation can improve
governance.

Thanks!

**Comment by luisdaniel** [comment]
done
