### ISSUE TITLE
Feb 10 Ideas Lunch - Eventbrite RSVP link

### ISSUE THREAD

**Issue by elh266** [GovLab/GovLab.org-Site#25]
Could you please add
https://www.eventbrite.com/e/govlab-ideas-lunch-w-sense-about-science-tickets-15601867606
to
http://thegovlab.org/ideas-lunch-page/
?

Thank you!

**Comment by luisdaniel** [comment]
Gonna need to teach you how to do these ¬_¬

:D

done.
