### ISSUE TITLE
od500 survey submission/display fix

### ISSUE THREAD

**Issue by aa-govlab** [GovLab/GovLab.org-Site#3]
Pls could there be a distinction between submitted surveys that are displayed & vetted vs. the ones that have been vetted but for some reason not displayed (or vice versa).

It would be EVEN better to have a distinct section for all those surveys that are _not_ displayed because they have actively been dropped.

Thanks Luis!

**Comment by luisdaniel** [comment]
wrong repo! yaaaay!
