### ISSUE TITLE
Banners

### ISSUE THREAD

**Issue by sverhulst** [GovLab/GovLab.org-Site#5]
Most of the banners seem to be about events that have already happened - Can we get his updated with some new (long term) features till we have some new events - One might be the Wiki - Other might be the Research Network  - Or any other relevant project -

**Comment by luisdaniel** [comment]
We can keep NHS, Academy, Digest, MacArthur. And we need two more to fill it up. Or we can just have four banners. We can also maybe recycle some of the old ones. 

If we want new ones, we'll have to get Claudio on that. 

For now, should I just remove the banners of previous events and leave the four I mentioned?

**Comment by sverhulst** [comment]
Sounds good  - we probably should have a few new ones as standard features that we can rotate on a regular basis -

**Comment by luisdaniel** [comment]
Let me keep this open, so I can use it as a to-do.

**Comment by luisdaniel** [comment]
left Academy, NHS, Digest, MacArthur, and OD500.
Any new ones, would need to be designed by Claudio. I'm sure we'll have an upcoming ideas luncheon soon.
