### ISSUE TITLE
State of the week

### ISSUE THREAD

**Issue by sverhulst** [GovLab/GovLab.org-Site#6]
Doesn't seem to change every week?

**Comment by luisdaniel** [comment]
notified andrew and shruti. they're on it.

**Comment by luisdaniel** [comment]
Closing this since I haven't heard anything further.

**Comment by sverhulst** [comment]
Fixed?

**Comment by luisdaniel** [comment]
Andrew says Shruti has collected a bunch of new stats and Andrew is working on formatting them in InDesign and they will start posting new ones every Monday starting this Monday.

**Comment by sverhulst** [comment]
Thanks
