### ISSUE TITLE
Add Samantha Grassle to the team page

### ISSUE THREAD

**Issue by laurenryu** [GovLab/GovLab.org-Site#8]
Link to headshot here: https://drive.google.com/a/thegovlab.org/file/d/0B5gYYOZe6KOJSHh2MU5xb2RRRms/edit?usp=sharing

Bio

Samantha is a GovLab Project Management Fellow. She joins the team after serving as a Google Policy Fellow with the American Association of People with Disabilities (AAPD). At the AAPD, she crafted the organizations public comment for the FCC’s recent Notice for Proposed Rulemaking on Protecting and Promoting the Open Internet.

Samantha earned her Masters degree in Public Administration from Columbia University. At Columbia, Samantha served as a capstone consultant for the Kosovo Ministry of Foreign Affairs, where she worked with a team of graduate students to develop a national digital diplomacy strategy. Samantha also served as a graduate policy intern at NYC Digital in the New York City Mayor's Office of Media and Entertainment. Here she contributed to the Bloomberg administration’s final digital roadmap, outlining the agency’s digital accomplishments and recommendations for the incoming administration. Samantha  also co-organized the first international Digital Cities Symposium, held at Internet Week NY. The event served as a global forum for city government practitioners to share best practices in digital development and innovation in the areas of access, education, engagement, open government, and industry.

**Comment by luisdaniel** [comment]
no access to picture. 
Also, picture needs to be in 3:2 ratio. 

Also, am in Mexico City for OD500 meeting. The following people also have access to do this:

Andrew
Dinorah
Jillian
Robyn
Arnaud
