### ISSUE TITLE
Add David Sangokoya to the team page

### ISSUE THREAD

**Issue by laurenryu** [GovLab/GovLab.org-Site#9]
Link to photo: https://drive.google.com/a/thegovlab.org/file/d/0B5gYYOZe6KOJVHdXaUttSEp5bjA/edit?usp=sharing

David recently graduated with a MPA degree from NYU Wagner. Prior to Wagner, David has worked with nonprofits in northern Uganda, Liberia, Namibia, and Sri Lanka. Building off his research and project experiences in post-conflict environments, David is interested in how data and technology can help governments protect the rights of the disadvantaged, make better allocation decisions, and create much needed mechanisms for good governance strategies.

**Comment by luisdaniel** [comment]
Andrew
Dinorah
Jillian
Robyn
Arnaud
